language: csharp
dist: trusty

sudo: false

script:
  - ./build.sh All

matrix:
  include:
    - mono: 4.8.1
      dotnet: 2.0.0
      env:
        - FSAC_TESTSUITE_NETCORE_MODE_STDIO=0
        - FSAC_TESTSUITE_NETCORE_MODE_HTTP=0
    - mono: 5.0.1
      dotnet: 2.0.0
      env:
        - FSAC_TESTSUITE_NETCORE_MODE_HTTP=0
    - mono: 5.2.0
      dotnet: 2.0.0
      env:
        - FSAC_TESTSUITE_CROSSGEN_NETFX=1 #works on 5.0
        - FSAC_TESTSUITE_NETCORE_MODE_HTTP=0
    - mono: latest # => "stable release"
      dotnet: 2.0.0
      env:
        - FSAC_TESTSUITE_CROSSGEN_NETFX=1 #works on 5.0
        - FSAC_TESTSUITE_NETCORE_MODE_HTTP=0
    - mono: weekly # => "latest commits"
      dotnet: 2.0.0
      env:
        - FSAC_TESTSUITE_CROSSGEN_NETFX=1 #works on 5.0
        - FSAC_TESTSUITE_NETCORE_MODE_HTTP=0

  allow_failures:
    - mono: latest
    - mono: weekly
