language: csharp
dist: trusty
dotnet: 1.0.4

mono:
 - 4.8.0
 - latest # => "stable release"
 - weekly # => "latest commits"

sudo: false

script:
  - ./build.sh Test
  - cd test/FsAutoComplete.IntegrationTests/DotNetCore
  - fsharpi Runner.fsx
  - dotnet build -v n sample1/c1
  - dotnet run -p sample1/c1/c1.fsproj

matrix:
  allow_failures:
    - mono: latest
    - mono: weekly
