language: csharp
dist: bionic

sudo: false

before_install:
  - |
    ./travis.sh
  - dotnet --info

script:
  - ./build.sh All

matrix:
  include:
    - mono: 5.18.0
      dotnet: 2.1.500
      env:
        - FSAC_TESTSUITE_CROSSGEN_NETFX=1 #works on 5.0
        - FSAC_TESTSUITE_NETCORE_MODE_HTTP=0
    - mono: latest # => "stable release"
      dotnet: 2.1.500
      env:
        - FSAC_TESTSUITE_CROSSGEN_NETFX=1 #works on 5.0
        - FSAC_TESTSUITE_NETCORE_MODE_HTTP=0
    - mono: weekly # => "latest commits"
      dotnet: 2.1.500
      env:
        - FSAC_TESTSUITE_CROSSGEN_NETFX=1 #works on 5.0
        - FSAC_TESTSUITE_NETCORE_MODE_HTTP=0
    - mono: 5.18.0
      dotnet: 2.2.103
      env:
        - FORCE_DOTNET_VERSION=2.2.103
        - FSAC_TESTSUITE_CROSSGEN_NETFX=1 #works on 5.0
        - FSAC_TESTSUITE_NETCORE_MODE_HTTP=0

  allow_failures:
    - mono: latest
    - mono: weekly
    - dotnet: 2.2.103
